In [1]:
import numpy as np
from GaussianElimination import gaussian_elimination
from LU import lu, lu_solve

In [2]:
A = np.array([
    [7.2, 2.3, -4.4, 0.5],
    [1.3, 6.3, -3.5, 2.8], 
    [5.6, 0.9, 8.1, -1.3],
    [1.5, 0.4, 3.7, 5.9]
])

b = np.array([15.1, 1.8, 16.6, 36.9])

In [3]:
L, U = lu(A)

In [4]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.18055556,  1.        ,  0.        ,  0.        ],
       [ 0.77777778, -0.15105027,  1.        ,  0.        ],
       [ 0.20833333, -0.01345291,  0.41213385,  1.        ]])

In [5]:
U

array([[ 7.2       ,  2.3       , -4.4       ,  0.5       ],
       [ 0.        ,  5.88472222, -2.70555556,  2.70972222],
       [ 0.        ,  0.        , 11.11354732, -1.27958461],
       [ 0.        ,  0.        ,  0.        ,  6.35964713]])

In [6]:
lu_solve(L, U, b)

array([ 3., -2.,  1.,  5.])

In [7]:
gaussian_elimination(A, b)

array([ 3., -2.,  1.,  5.])